name: Manage Stale Issues - Testing Version

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
  mark_and_close_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 1
          days-before-close: 1
          stale-issue-message: 'This issue has been automatically marked as stale because it has 
          not had recent activity. It will be closed if no further activity occurs. Feel free to 
          reopen it or create a new issue if you wish to continue contributing.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it 
          has not had recent activity. It will be closed if no further activity occurs. Feel free
           to reopen it or create a new pull request if you wish to continue contributing.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'p.Urgent,s.OnHold'
          exempt-pr-labels: 'p.Urgent,s.DoNotMerge,s.FinalReview,s.OnHold'
          operations-per-run: 30
